// Generated by CoffeeScript 2.4.1
(function() {
  var addCL, content, display, pA, workWithDOM;

  pA = [0, 0, 0, 0, 0];

  content = null;

  display = function() {
    return content.innerHTML = pA;
  };

  addCL = function(item) {
    return item.onclick = function() {
      switch (item.innerText) {
        case 'Молоко':
          pA[0]++;
          break;
        case 'Сметана':
          pA[1]++;
          break;
        case 'Творог':
          pA[2]++;
          break;
        case 'Масло':
          pA[3]++;
          break;
        case 'Сыр':
          pA[4]++;
      }
      return display();
    };
  };

  workWithDOM = function() {
    var i, item, items, len, results;
    items = document.getElementsByTagName('item');
    content = document.getElementsByTagName('content')[0];
    results = [];
    for (i = 0, len = items.length; i < len; i++) {
      item = items[i];
      results.push(addCL(item));
    }
    return results;
  };

  window.addEventListener('load', function() {
    return workWithDOM();
  });

}).call(this);
